"""Build a conversation manifest (yaml) for non-destructive DAgger rounds (C3).

The LLaVA dataset natively accepts a yaml manifest of conversation files with
per-file sampling (see LLaVANuScenesDataset._load_conversation_data). Instead of
merging each DAgger round INTO carla_conversations.json (mutating the base), keep
one file per round and list them here. Each round then ADDS a file and appends a
line to the manifest — the base is never rewritten.

Scans data_carla/processed/ for:
  carla_conversations.json          -> the base fit
  dagger_r*_conversations.json      -> one per DAgger round

and writes data_carla/processed/conversations.yaml. Train against it with:
  bash scripts/train_carla_parking.sh   (point --conversations at the yaml)

Idempotent: re-running regenerates the same manifest deterministically.

Run from the repo root:
  python scripts/build_conversation_manifest.py
"""

import argparse
import re

import paths

PROC = paths.PROCESSED_DIR


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(PROC / "conversations.yaml"))
    ap.add_argument("--sampling", default="all",
                    help="Sampling strategy applied to every file (e.g. all, random:5000).")
    args = ap.parse_args()

    entries = []
    base = PROC / "carla_conversations.json"
    if base.exists():
        entries.append(base)
    # Deterministic order: sort dagger round files by round number.
    dagger = sorted(PROC.glob("dagger_r*_conversations.json"),
                    key=lambda p: int(re.search(r"dagger_r(\d+)_", p.name).group(1)))
    entries.extend(dagger)

    if not entries:
        raise SystemExit(f"No conversation files found under {PROC}")

    lines = ["# Auto-generated by scripts/build_conversation_manifest.py",
             "# Each DAgger round adds a file here; the base is never rewritten.",
             "datasets:"]
    for p in entries:
        lines.append(f"  - json_path: {p}")
        lines.append(f"    sampling_strategy: {args.sampling}")
    open(args.out, "w").write("\n".join(lines) + "\n")

    print(f"Wrote {args.out} with {len(entries)} file(s):")
    for p in entries:
        print(f"  - {p.name}")


if __name__ == "__main__":
    main()
